# Reloads all unit files.  Basically a soft restart.  Has not been tested 12/21/2018
- name: reload systemd
  become: yes
  become_method: sudo  
  command: systemctl daemon-reload

- name: Restart ssh
  service: name=ssh state=restarted
