---
  - name: install common packages
    action: apt pkg={{item}} state=installed
    with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - locales
    - build-essential
    - acl
    - ntp
    - htop
    - git
    - supervisor
    - python-pip
    - python3-pip
    - nginx
    notify: reload systemd  # Tested on Pi-Stack already configured from Master Branch
  
  - name: Check Rasp model
    command: cat /proc/device-tree/model
    register: piversion
  - name: Debug each entry of my hosts
    debug:
      msg: "System {{ inventory_hostname }} is a {{ piversion.stdout }}"