---
  - name: install common packages
    action: apt pkg={{item}} state=installed
    with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - locales
    - build-essential
    - acl
    - ntp
    - htop
    - git
    - supervisor
    - python-pip
    - python3-pip
    - nginx
    - rpi-update
    notify: reload systemd  # Tested on Pi-Stack already configured from Master Branch
  
  - name: Check Rasp model
    command: cat /proc/device-tree/model
    register: piversion
  - name: Debug each entry of my hosts
    debug:
      msg: "System {{ inventory_hostname }} is a {{ piversion.stdout }}"

  # - name: Run kernel upgrade (this can take up to 10 minutes)
  #   command: /usr/bin/rpi-update
  #   register: rpiupdate
  #   tags:
  #     - system-upgrade

  - name: 'Update APT package cache'
    action: apt update_cache=yes

  - name: 'Upgrade APT to the lastest packages'
    action: apt upgrade=safe

  - name: 'Reboot'
    shell: sleep 2 && reboot
    async: 1
    poll: 0
    ignore_errors: true

  - name: "Wait for Raspberry PI to come back"
    local_action: wait_for host={{ real_ansible_host }} port=22 state=started delay=10
    become: false