---
  - name:    Install prerequisites
    apt:     
      name: "{{item}}"
      state:  present
    with_items:
     - apt-transport-https
     - ca-certificates
     - curl
     - software-properties-common
  - name:    Add Docker GPG key
    apt_key: 
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: Clean Docker files to be idempotent
    file:
      name: "{{ item }}"
      state: absent
    with_items:
      - /etc/apt/sources.list.d/docker.list
      - /etc/apt/sources.list.d/kubernetes.list

  - name: Recreate Docker files
    file:
      name: "{{ item }}"
      state: touch
    with_items:
      - /etc/apt/sources.list.d/docker.list

  - name: Add Docker to the list of repositories
    lineinfile:
      dest: /etc/apt/sources.list.d/{{ item.category }}.list
      line: "{{ item.url }}"
    with_items:
      - { url: 'deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable', category: 'docker'     }

  - name: Install packages to allow apt to use HTTPS repositories
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - apt-transport-https
      - ca-certificates
      - software-properties-common

  - name: Update list of available repositories
    apt: 
      update_cache: yes

  - name: Update all packages to the latest version
    apt:
      upgrade: dist

  - name: Determine if docker is installed
    stat:
      path: /usr/bin/docker
    register: docker_there
    ignore_errors: True

  - name:    Install Docker
    apt:     
      name: docker-ce
    when: docker_there.stat.exists == False

  - name: Ensure Docker is started.
    service:
      name: docker
      state: started
      enabled: yes