version: "3"
services:
  visualizer:
    image: alexellis2/visualizer-arm:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.backend=visualizer"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:viz.grablin.lan"
    networks:
      - traefik
networks:
  traefik:
    external: true